### PR TITLE
Read scene data from LZ4-compressed files

### PR DESCRIPTION
**Pull request by MoritzBrueckner**

### CODE REVIEW

**Comment by luboslenco** [comment]
Thanks! Which targets did you test on? For js the `Bytes.ofData()` should take an [ArrayBuffer](https://api.haxe.org/haxe/io/BytesData.html), so there is a bug in the current `Lz4.encode()` revision as well.

**Comment by MoritzBrueckner** [comment]
Hi, I tested it on Krom and HTML5, windows-hl triggered a breakpoint but also for the master branch. Those three are the only targets I can test currently. I will take a look at it tomorrow (no time today), thanks!

**Comment by luboslenco** [comment]
👍 No rush at all.

If I change it from `return Bytes.ofData(cast oBuf);` to `return Bytes.ofData(untyped oBuf.buffer);` all is working good in ArmorPaint. But for HL my guess is `return Bytes.ofData(oBuf.getData());`.

**Comment by MoritzBrueckner** [comment]
There might be the issue that there are some platforms where the Kha arrays don't have functions to access the underlaying data, yet Armory uses Krom (js), node (js) and HL only so this is probably not a big problem. But: for custom targets (which are supported too) this would be problematic.

The `Bytes` class has a method to allocate a new Bytes instance which we could fill manually to support all platforms, but this would be a bit slower because of the duplication of the arrays... Should we default to that if we are on another platform than js or HL?

**Comment by luboslenco** [comment]
Sure.

**Comment by MoritzBrueckner** [comment]
Pushed a fix :)

**Comment by luboslenco** [comment]
Awesome!

I pushed one more change at https://github.com/armory3d/iron/commit/d0889f1c55143b5d73e91ae252e7fcf41ec1152c as I did not get it to work in ArmorPaint. The `oBuf.subarray(0, oPos).buffer` should be the same as `oBuf.buffer`, as [subarray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray) only creates a new view on the same buffer. Changed to [buffer.slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/slice).

**Pull request merged**
