### PR TITLE
Create Uniforms Manager class

### PR DESCRIPTION
**Pull request by QuantumCoderQC**
Required by https://github.com/armory3d/armory/pull/2232

Adds a new class to improve managing uniform constants.

### CODE REVIEW

**Comment by luboslenco** [comment]
Yo, it's awesome but please move `UniformsManager` to Armory, so iron stays as small as possible. Thanks!

**Comment by QuantumCoderQC** [comment]
Hi @luboslenco , thank you for your feedback!

The main reason I put `UniformsManager` class in `iron` was so that I could add the materials and parameters to the look-up maps when the materials are spawned. This must be done to set the uniform values to their default values. Otherwise, the uniforms are not properly initialized and have a null value.

Also, I have to remove these materials from the  look-up maps when objects are removed from the scene. Otherwise these maps still retain the key value pairs even after objects are removed.

Likewise, when a scene is removed/replaced, the corresponding maps must also be removed.

I could not find a better way of doing the above within Armory. It would be awesome if you could please suggest a way to go about this.

Best Regards,
QC

**Comment by knowledgenude** [comment]
@QuantumCoderQC , Hi! Sorry for intruding. I guess he mean there is no problem leaving the necessary lines in `Iron`, so only moving the `UniformsManager` class to `Armory` should be sufficient :)

**Comment by QuantumCoderQC** [comment]
Hi, @knowledgenude . Thanks for the comment.

Yes, I did understand what he meant. But if I move just the class to armory, I will no longer be able to register the shader uniforms for each material inside of iron with:

`UniformsManager.registerShaderUniforms(mat); // Register shader material parameters to map`

But, since when I asked for a better method of doing this, I have discovered a few ways to come around this. Will implement it when I get some time.

**Comment by luboslenco** [comment]
Yes, only the UniformsManager class. If needed a callback can be added where necessary.

**Pull request closed without merging**
